SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE LEFT(SEX_UPON_INTAKE, 1) = 'I' AND 
    SEX_UPON_INTAKE != SEX_UPON_OUTCOME
ORDER BY O.ANIMAL_ID ASC