WITH CP AS (
    SELECT C.CAR_ID, C.CAR_TYPE, ROUND(
        C.DAILY_FEE * 30 * ((100 - P.DISCOUNT_RATE) / 100) 
        , 0 )AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
            ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV') AND 
        P.DURATION_TYPE = '30일 이상'
)

SELECT CP.CAR_ID, CP.CAR_TYPE, CP.FEE
FROM CP
WHERE CP.FEE BETWEEN 500000 AND 1999999 AND 
    CP.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE '2022-11-02' < END_DATE AND START_DATE < '2022-12-01'
    )
ORDER BY CP.FEE DESC, CP.CAR_TYPE ASC, CP.CAR_ID DESC