WITH RECURSIVE HOUR_TALE AS (
    SELECT 0 AS 'HOUR'
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM TIMETALE
    WHERE HOUR < 23
)

SELECT TIMETALE.HOUR, IFNULL(OUTS.COUNT, 0) AS 'COUNT'
FROM TIMETALE
    LEFT JOIN (
        SELECT HOUR(DATETIME) AS 'HOUR', COUNT(*) AS 'COUNT'
        FROM ANIMAL_OUTS
        GROUP BY HOUR(DATETIME)
    ) AS OUTS
        ON TIMETALE.HOUR = OUTS.HOUR