SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        ON C.CAR_ID = H.CAR_ID
WHERE '10' <= MONTH(H.START_DATE) AND C.CAR_TYPE = '세단'
GROUP BY H.CAR_ID
ORDER BY C.CAR_ID DESC