SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
    SUM(S.COUNT * B.PRICE) AS TOTAL_SALES
FROM (
    SELECT BOOK_ID, SUM(SALES) AS 'COUNT'
    FROM BOOK_SALES
    WHERE MONTH(SALES_DATE) = '01'
    GROUP BY BOOK_ID
) AS S
    JOIN BOOK AS B
        ON S.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR AS A
        ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC