SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, 
    U.GENDER, COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM ONLINE_SALE AS O
    JOIN ( 
        SELECT USER_ID, GENDER
        FROM USER_INFO 
        WHERE GENDER IS NOT NULL
    ) AS U
        ON O.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC