SELECT H.HISTORY_ID, 
    ROUND(C.DAILY_FEE * H.DATE_DIFF * 
    CASE
        WHEN H.DATE_DIFF >= 90
            THEN 0.85
        WHEN H.DATE_DIFF >= 30
            THEN 0.92
        WHEN H.DATE_DIFF >= 7
            THEN 0.95
        ELSE 1
    END) AS FEE
FROM (
    SELECT HISTORY_ID, CAR_ID, 
        DATEDIFF(END_DATE, START_DATE) + 1 AS DATE_DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS H 
    JOIN CAR_RENTAL_COMPANY_CAR AS C
        ON H.CAR_ID = C.CAR_ID
    JOIN (
        SELECT CAR_TYPE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    ) AS P
        ON C.CAR_TYPE = P.CAR_TYPE 
WHERE C.CAR_TYPE = '트럭'
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC