WITH INFO AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT SALE.YEAR, SALE.MONTH, COUNT(SALE.USER_ID) AS PUCHASED_USERS, (
        SELECT ROUND(COUNT(SALE.USER_ID) / COUNT(USER_ID), 1)
        FROM INFO
    ) AS PUCHASED_RATIO
    FROM INFO
        JOIN (
            SELECT USER_ID, SALES_AMOUNT, YEAR(SALES_DATE) AS 'YEAR', 
                MONTH(SALES_DATE) AS 'MONTH'
            FROM ONLINE_SALE 
            GROUP BY MONTH(SALES_DATE), USER_ID
        ) AS SALE
            ON INFO.USER_ID = SALE.USER_ID
GROUP BY SALE.MONTH
ORDER BY SALE.YEAR ASC, SALE.MONTH ASC