WITH INFO AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT SI.YEAR, SI.MONTH, COUNT(*) AS PUCHASED_USERS,
	ROUND((
        COUNT(*) / (
        SELECT COUNT(*)
		FROM INFO
        )), 1) AS PUCHASED_RATIO
FROM (
    SELECT DISTINCT YEAR(S.SALES_DATE) AS 'YEAR', 
        MONTH(S.SALES_DATE) AS 'MONTH', S.USER_ID
    FROM ONLINE_SALE AS S
        JOIN INFO AS I
            ON S.USER_ID = I.USER_ID
) AS SI
GROUP BY SI.MONTH
ORDER BY SI.MONTH