# JOIN
SELECT O.REST_ID, O.REST_NAME, O.FOOD_TYPE, O.FAVORITES, O.ADDRESS,
ROUND(AVG(W.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO O
    JOIN REST_REVIEW W
        ON O.REST_ID = W.REST_ID
WHERE LEFT(O.ADDRESS, 2) = '서울'
GROUP BY W.REST_ID
ORDER BY SCORE DESC, O.FAVORITES DESC